config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resource :accounts
  get "user/me", to: "user#me", as: "my_settings"
  patch "users/update_me", to: "users#update_me", as: "update_my_settings"
  get "user/password", to: "users#password", as: "my_password"
  patch "user/update_password", to: "users#update_password", as: "my_update_password"

  scope "account", as: "account" do
    resources :users
  end

  get "support/contact"
  get "activity/mine"
  get "activity/feed"

  root to: "activity#mine"
end

app/models/account.rb
class Account < ApplicationRecord
  resourcify
  has_many :users
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/friendlyable.rb
module Friendlyable
  extend ActiveSupport::Concern

  included do
    extend ::FriendlyId
    before_create :set_hash_id
    friendly_id :hash_id
  end

  def set_hash_id
    hash_id = nil
    loop do
      hash_id = SecureRandom.urlsafe_base64(9).gsub(/-|_/, ("a".."z").to_a[rand(26)])
      break unless self.class.name.constantize.where(:hash_id => hash_id).exists?
    end
    self.hash_id = hash_id
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :account, optional: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    redirect_to root_path unless current_user.account.nil?
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)

    if @account.save
      current_user.account = @account
      current_user.add_role(:admin, @account)
      current_user.save
      redirect_to root_path, success: "Your account has been created!"
    else
      render :new
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :addr1, :addr2, :city, :state, :zip, :country)
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def mine
  end

  def feed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  layout :layout_by_resource

  helper_method :current_account

  def current_account
    @current_account ||= current_user.account
    @current_account
  end

  protected

  def layout_by_resource
    devise_controller? ? "devise" : "application"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_params

  protected

  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path_for(resource)
    new_accounts_path
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:index]

  def index
  end

  def show
  end

  def new
    @user = User.new
    set_choices
  end

  def create
    @user = User.unscoped.new(user_params.except("role"))
    @user.account = current_account
    @user.password = "password123"

    respond_to do |format|
      begin
        if @user.valid? && @user.invite!(current_user)
          @user.add_role(user_params[:role].to_sym, current_account)
          format.html {
            redirect_to(account_users_path,
                        notice: "User was successfully invited.")
          }
        else
          set_choices
          format.html { render :new }
        end
      rescue ActiveRecord::RecordNotUnique
        flash[:alert] = "Email must be unique"
        format.html { render :new }
      end
    end
  end

  def edit
    set_choices
  end

  def me
    @user = current_user
  end

  def password
    @user = current_user
  end

  def update_password
    @user = current_user
    respond_to do |format|
      if @user.update(user_password_params)
        bypass_sign_in(@user)
        format.html {
          redirect_to(my_password_path, notice: "Password was successfully updated.")
        }
      else
        format.html { render :edit }
      end
    end
  end

  def update_me
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        bypass_sign_in(@user)
        format.html {
          redirect_to(my_settings_path, notice: "Your information was successfully updated.")
        }
      else
        format.html { render :me }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params.except("role"))
        format.html {
          redirect_to(account_users_path,
                      notice: "User was successfully updated.")
        }
      else
        set_choices
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html {
        redirect_to(account_users_path, notice: "User was successfully destroyed.")
      }
      format.json { head(:no_content) }
    end
  end

  private

  def set_users
    @users = current_account.users
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def set_choices
    @choices = []
    @choices << ["Admin", "admin"]
    @choiches << ["User", "user"]
  end

  def user_params
    params.require(:user).permit(:name, :email, :role, :time_zone)
  end

  def user_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info",
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, msg|
      next if msg_type == :form_error
      concat(content_tag(:div, msg.html_safe, {
        class: "alert #{bootstrap_class_for(msg_type)} fade in",
      }) do
        concat content_tag(:button, "x", class: "close", data: { dismiss: "alert" })
        concat msg.html_safe
      end)
    end
    nil
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.sum("") { |msg| content_tag(:li, msg) }
    notice = I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block alert-fixed">
      <h4>#{notice}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/new.html.slim
.row
  .col-lg-12
    .box
      .box-header
        h2
          | New Account Information
      .box-body
        = form_for @account, html: { class: "form-horizontal" } do |f|
          - if @account.errors.any?
            .alert.alert-error.alert-block.alert-fixed
              h4 = "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
              == @account.errors.full_messages.sum("") { |msg| content_tag(:li, msg) }
          .form-group
            = f.label :name, class: "control-label col-lg-2"
            .col-lg-10
              = f.text_field :name, placeholder: "Enter your Account's Name", class: "form-control"
          
          .form-group
            .col-lg-offset-2.col-lg-10
              = f.submit "Save", class: "btn btn-primary"

app/views/activity/feed.html.slim
h1 Activity#feed
p Find me in app/views/activity/feed.html.slim

app/views/activity/mine.html.slim
h1 Activity#mine
p Find me in app/views/activity/mine.html.slim

app/views/layouts/application.html.slim
doctype HTML
HTML
  head
    title Standup Kid
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all',\
     'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag href=\
    "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"

  body.fixed.skin-blue-light
    .wrapper
      = render 'layouts/navigation/layout'
      .content-wrapper
        = flash_messages
        = yield
      = render 'layouts/navigation/footer'

app/views/layouts/devise.html.slim
doctype html
html
  head
    title Standup Kid
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all',\
     'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag href=\
    "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"

  

  body.login-page
    = flash_messages
    = yield

app/views/layouts/navigation/_footer.html.slim
footer.main-footer
  .pull-right.hidden-xs
    | Standup Kid
  strong
    | Copyright © 2016
    a href="#" Kelson Warner
  | All rights reserved.

app/views/layouts/navigation/_header.html.slim
header.main-header
  a.logo href="/"
    | Standup App  
  .nav.navbar.navbar-static-top role="navigation"
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.dropdown.messages-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-envelope-o
            span.label.label-success 4
          ul.dropdown-menu
            li.header You have 4 messages
            li
              ul.menu
                li
                  a href="#"
                  .pull-left
                    img.img-circle [ alt=("User Image")
                    src="http://placehold.it/160x160" ]
                  h4
                    | Sender Name
                    small
                      i.fa.fa-clock-o
                      | 5 mins
                  p Message Excerpt
            li.footer
              a href="#"  See All Messages
        li.dropdown.notifications-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-bell-o
            span.label.label-warning 10
          ul.dropdown-menu
            li.header You have 10 notifications
            li
              ul.menu
                li
                  a href="#"
                    i.ion.ion-ios-people.info
                    | Notification title
            li.footer
              a href="#"  View all
        li.dropdown.tasks-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-flag-o
            span.label.label-danger 9
          ul.dropdown-menu
            li.header You have 9 tasks
            li
              ul.menu
                li
                  a href="#"
                  h3
                    | Design some buttons
                    small.pull-right 20%
                  .progress.xs
                    .progress-bar.progress-bar-aqua [ aria-valuemax="100"
                    aria-valuemin="0" aria-valuenow="20" role="progressbar"
                    style=("width: 20%") ]
                      span.sr-only 20% Complete
            li.footer
              a href="#"  View all tasks
        li.dropdown.user.user-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            img.user-image alt=("User Image") src="http://placehold.it/160x160"
            span.hidden-xs Kelson Warner
          ul.dropdown-menu
            li.user-header
              img.img-circle [ alt=("User Image")
              src="http://placehold.it/160x160" ]
              p
                | Kelson Warner - Web Developer
                small Member since Nov. 2012
            li.user-body
              .col-xs-4.text-center
                a href="#"  Followers
              .col-xs-4.text-center
                a href="#"  Sales
              .col-xs-4.text-center
                a href="#"  Friends
            li.user-footer
              .pull-left
                a.btn.btn-default.btn-flat href="#"  Profile
              .pull-right
                a.btn.btn-default.btn-flat href="#"  Sign out

app/views/layouts/navigation/_layout.html.slim
= render "layouts/navigation/header"
= render "layouts/navigation/sidebar"

app/views/layouts/navigation/_sidebar.html.slim
.main-sidebar
  .sidebar
    .user-panel
      .pull-left.image
        img.img-circle alt=("User Image") src="http://placehold.it/160x160" /
      .pull-left.info
        p User Name
        a href="#"
          i.fa.fa-circle.text-success
          | Online
    form.sidebar-form action="#" method="get"
      .input-group
        input.form-control name="q" placeholder="Search..." type="text" /
        span.input-group-btn
          button#search-btn.btn.btn-flat name="search" type="submit"
            i.fa.fa-search
    ul.sidebar-menu
      li.header HEADER
      li.active
        a href="#"
          span Link

      li
        a href="#"
          span Another Link
      li.treeview
        a href="#"
          span Multilevel
          i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          li
            a href="#"  Link in level 2
          li
            a href="#"  Link in level 2

app/views/support/contact.html.slim
h1 Support#contact
p Find me in app/views/support/contact.html.slim

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/index.html.slim
.content-header
  h2 Users
.content
  .row
    .col-lg-12
      .box.box-primary
        .box-header
          h3.box-title
            = "Users in #{current_account.name}"
        .box-body
          .table-responsive
            table.table.table-striped
              thead
                tr
                  th Name
                  th Email
                  th Status
                  th Role
                  th Added at
                  th
              tbody
                - @users.each do |user|
                  tr
                    td = user.name
                    td = user.email
                    td = user.accepted_or_not_invited? ? "Active" : "Invited"
                    td = user.account.roles&.first&.name&.capitalize
                    td = user.created_at.strftime('%D')
                    td
                      = link_to('Edit', edit_account_user_path(user), class: 'btn btn-default btn-xs')
                      = link_to('Destroy', { method: :delete, data: { confirm: 'Are you sure?' } }, class: 'btn btn-warning btn-xs') unless user.id == current_user.id
        .box-footer style="height: 55px;"
          span.pull-right
            a.btn.btn-primary href="#{new_account_user_path}"
              | Add User

app/views/users/new.html.slim
h1 Users#new
p Find me in app/views/users/new.html.slim

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim

app/views/users/update.html.slim
h1 Users#update
p Find me in app/views/users/update.html.slim